version: '3'

services:
  frontend_service:
    build: FrontUsers
    ports:
      - "3000:3000"

  backend_service:
    build: BackUsers
    ports:
      - "8484:8484"
    depends_on:
      - database_service
    
  database_service:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - 1521:1521
